apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c8vak3z51-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c8vak3z51-python 
  name: c8vak3z51-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c8vak3z51-python 
